name: Build macOS App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: aarch64-apple-darwin

      - name: Add x86_64-apple-darwin target
        run: rustup target add x86_64-apple-darwin

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Tauri CLI
        run: npm install @tauri-apps/cli

      - name: Build for macOS
        run: npm run tauri build -- --target universal-apple-darwin

      - name: List build output
        run: ls -R src-tauri/target/universal-apple-darwin/release/bundle/macos/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: src-tauri/target/universal-apple-darwin/release/bundle/macos/*.app
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
